### ISSUE TITLE
Monika Corpus

### ISSUE THREAD

**Issue by sr229** [ClarityCafe/Ivy#5]
We'll probably need collaboration with a Monika-centric DDLC Mod as we require a solid database for Monika.

Here's some data points to gather for the corpus : 

- [ ] @lilmonix3 Twitter Data
- [ ] Mainline DDLC
- [ ] Monika After Story
- [ ] Related Citations

**Comment by sr229** [comment]
@not0xFF compiled some mainline DDLC dialog for us but it was created before this tracker was made.

**Comment by sr229** [comment]
Please be reminded we need to complement the current dataset with Monika After Story dataset and some pieces from Cornell if possible

**Comment by sr229** [comment]
reverting to zero progress because of #6

**Comment by IronworksProductions** [comment]
I Have an Idea. What about since this is trying to 'become' monika we can have this listen in on the background of MAS listening into everything that is hard coded and then trying to replicate it. Once it replicates accurately enough times we can activate it as a beta protocol that way instead of it being hard coded like MAS dialogflow is so far, it eventually learns to do it on its own. 
What would be required?
A way to link into MAS passively listening into every conversation monika makes so it can learn to replicate them.
We can also run it through simulations of the dialog flow database as it is now since it should be pretty big judging by how popular the mod is.
That would give Rebecca an edge that nothing has right now.

Edit: It looks like you already have a way to link into MAS but i'm not sure you were going to use it in this way.

**Comment by sr229** [comment]
@nacjm plan is to have it a opt-in switchable feature for MAS, but we didn't plan to actually make it learn on hardcoded dialogue as it is design to learn from a pre-trained dataset.

**Comment by sr229** [comment]
This now concerns MonikChat - migrating issue.
